### ISSUE TITLE
Changing rootProject.name does not update GA of VersionEye project 

### ISSUE THREAD

**Issue by sslavic** [stempler/gradle-versioneye-plugin#19] opened 2016-03-04 09:24 UTC
Using id 'org.standardout.versioneye' version '1.2.0' plugin, after changing rootProject.name, and running versioneye-update task, VersionEye project GA did not get updated.

**Comment by stempler** [comment] 2016-03-06 15:34
@reiz Is that update supposed to happen when posting to `/v2/projects/{project_id}`? If yes, might that be fixed by implementing #9?

**Comment by stempler** [comment] 2016-03-20 12:50
My tests seem to confirm that this is an issue with the API, the updated name in the uploaded `pom.xml` or `pom.json` is ignored.
@reiz Can you give any feedback if it's intended that way or confirm that it is a VersionEye API bug?

**Comment by reiz** [comment] 2016-03-30 11:17
@stempler Yes. Currently the name from the pom.json is ignored. That's by design. Because if you rename your project via the VersionEye web interface you don't want it to get reseted by fresh uploads through the API.

**Comment by sslavic** [comment] 2016-03-30 11:57
@reiz maybe versioneye server could keep separate information - was project renamed in server or not. When plugins try to update project in VersionEye, if project wasn't renamed in server then use/apply name from pom.json, and ignore it if project was renamed in server.

**Comment by stempler** [comment] 2016-04-09 10:01
@reiz But project name and GA seem to be separate - I can change the name, but not the GA, so maybe the GA should be updated via the `pom.json`?

**Comment by stempler** [comment] 2016-04-24 10:18
Closing this because this is an issue with the behavior of the VersionEye API and not the plugin.

**Closed by stempler** 2016-04-24 10:18 UTC
